#!/bin/bash

# Using loops

# Get a random number 0 < target < 100
declare -ir target=$(( ($RANDOM % 100) + 1 )) # Using arithmetic sustitutions

# Initilize guess var
declare -i guess=0

until (( guess == target )); 
do
    read -p "Take a guess: " guess
    
    # if guess is 0 it was not a number
    (( guess )) || continue

    if  (( guess < target ));
    then
        echo "Higher!"
    elif (( guess > target )); 
    then
        echo "Lower!"
    else
        echo "You found it!"
    fi
done

exit 0