#!/bin/bash
# -x to debug a script or a part of a script

# Getting the date
declare -r date=$(date)

# set -x # enabling debugging
# Getting the topic
declare -r topic="$*"
# set +x # disabling debbuging

# Filename to save notes
declare -r filename="./${topic}-note.txt"

# Checking if file exist, if not create it
[[ ! -d $filename ]] && touch "$filename" 2> /dev/null || { echo "Cannot create file $filename" 1>&2; exit 1; }

# Is file writable?
[[ -w $filename ]] || { echo "File $filename not writable" 1>&2; exit 1; }

# Prompting user for note
read -p "Your note: " note

if [[ $note ]]; 
then
    echo "$date: $note" >> "$filename"
    echo "Note '$note' saved to $filename"
else
    # Using redirection
    echo "No input: note wasn't saved." 1>&2 # or > /dev/stderr
fi
